### ISSUE TITLE
crc32cer_nif_not_loaded

### ISSUE THREAD

**Issue by fxn** [bbalser/elsa#52]
Hi! I guess this is a quirk in my setup, but don't know what do to.

I am setting up a very simple project in which there is only one producer and one topic. This error is raised whenever I try to send a message:

```
13:42:05.980 [error] GenServer #PID<0.845.0> terminating
** (stop) {:crc32cer_nif_not_loaded, '/app/_build/test/lib/crc32cer/priv/crc32cer'}
    :erlang.nif_error({:crc32cer_nif_not_loaded, '/app/_build/test/lib/crc32cer/priv/crc32cer'})
    (crc32cer) src/crc32cer.erl:23: :crc32cer.nif/2
    (kafka_protocol) src/kpro_batch.erl:97: :kpro_batch.encode_tx/4
    (kafka_protocol) src/kpro_batch.erl:47: :kpro_batch.encode/3
    (kafka_protocol) src/kpro_req_lib.erl:206: :kpro_req_lib.produce/5
    (brod) src/brod_producer.erl:262: anonymous fn/8 in :brod_producer.init/1
    (brod) src/brod_producer_buffer.erl:273: :brod_producer_buffer.do_send/4
    (brod) src/brod_producer.erl:470: :brod_producer.maybe_produce/1
    (brod) src/brod_producer.erl:422: :brod_producer.do_handle_produce/3
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:produce, {:brod_call_ref, #PID<0.1077.0>, #PID<0.845.0>, #Reference<0.3295147349.1708916740.261212>}, [%{key: "", ts: 1573134125638, value: "test value"}], :undefined}
```

According to the Hex output, `crc32cer` is compiled just fine, and the rest of the app works. This is happening inside a Docker container and dependendencies are stored in a `/mix` volume, in case that matters.

Please, if I should ask in `brod` or `crc32cer` better just tell me!

**Comment by fxn** [comment]
Not happening anymore. Don't know what happened, but closing by now.

**Comment by fxn** [comment]
Sorry, the problem was not gone, but the error traces where not shown. Here's the problem again:

```
iex(1)> Elsa.produce(:driver_telemetry_connection, "driver-telemetry-events", "value")
[debug] Elixir.Elsa.Producer Sending 1 messages to driver-telemetry-events:0
[info] client :driver_telemetry_connection connected to kafka:9092

[error] GenServer #PID<0.337.0> terminating
** (stop) {:crc32cer_nif_not_loaded, '/app/_build/dev/lib/crc32cer/priv/crc32cer'}
    :erlang.nif_error({:crc32cer_nif_not_loaded, '/app/_build/dev/lib/crc32cer/priv/crc32cer'})
    (crc32cer) src/crc32cer.erl:23: :crc32cer.nif/2
...
```

where

```
# ls _build/dev/lib/crc32cer/priv
crc32cer.so  crc32cer_drv.so
```

and this was compiled from scratch inside the container.

Does it ring any bell?

**Comment by scrogson** [comment]
@fxn this is a NIF dependency in the [`kafka_protocol`](https://hex.pm/packages/kafka_protocol) package. I don't think this is an issue with Elsa.

**Comment by fxn** [comment]
OK, I'll report in a different project. Thanks anyway.

**Comment by jdenen** [comment]
@fxn 

Yeah not an elsa issue, but I have seen something like this before. It was caused by a Docker/host OS mismatch. I know you said it was compiled from scratch inside the container, but I'd triple check that some layer caching nonsense isn't coming into play.

**Comment by fxn** [comment]
@jdenen thanks!

I guess that is what happened. I reset everything Docker, deleted `_build` and `_deps` and the problem disappeared. I suspect the `.so` file was in `deps` and I compiled by error in the host early in the project.

**Comment by jdenen** [comment]
Yeah, that sounds like exactly what happened to me. Adding `_build` and `deps` to our `.dockerignore` ensured it never happened to us again.
