### ISSUE TITLE
Provide example app

### ISSUE THREAD

**Issue by mackeyja92** [bbalser/elsa#82]
Hey, thanks for your work on this project!

I think a full example app showing the ideal way to run and configure elsa would do wonders for people trying to get started using the library. I have found myself with a few questions that the documentation isn't super clear on that an example app would solve.

Thank you again!

**Comment by jdenen** [comment]
Hey @mackeyja92, thanks for the issue. I should be able to knock one of these out pretty quick. I'll let you know when it's up.

**Comment by jdenen** [comment]
You can find an example app [here](https://github.com/jdenen/let_it_go). I'm interested to hear your feedback around two things:

1. Does this help?
2. What about this example application is more helpful than the docs?

I'd like to fix the documentation to be more helpful if at all possible. Thanks!

**Comment by mackeyja92** [comment]
@jdenen Thanks for the example, this clarified it greatly.
