### ISSUE TITLE
Support for SASL Authentication

### ISSUE THREAD

**Issue by vittoriabitton** [bbalser/elsa#91]
Hi there!

Is there a way to add SASL authentication in the configuration? There is support for such?

Thanks in advance!

**Comment by jeffgrunewald** [comment]
Hi @vittoriabitton, good question! Check out https://github.com/bbalser/elsa/issues/61 and let us know if that covers your configuration needs to with via SASL. On the client side it’s relatively simple but there is also a broker-side configuration that you’ll need to verify to make sure everything is working as desired. Let us know if that doesn’t meet your needs.

**Comment by jdenen** [comment]
Looks like you got it figured out in #61 so I'm closing this issue.
